version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.1

    working_directory: /go/src/github.com/VerstraeteBert/WeatherApp
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/cmd/dep
    - run:
        name: run build
        command: |
          dep ensure
          go build ./...
    - run:
      name: Ensure correctly vetted code
      command: go vet ./...
    - run:
        name: Ensure correctly linted (go fmt)
        command: go fmt ./...
