version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.1
    - image: circleci/mysql:5.7
      environment:
        DB_NAME: "circle_test"
        DB_USER: "root"
        DB_PASS: ""
        DB_HOST: "localhost"
        DB_PORT: "3306"

    working_directory: /go/src/github.com/VerstraeteBert/WeatherApp
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/cmd/dep
    - run: go get -u github.com/golang-migrate/migrate/cli

      #  CircleCi's Go Docker image includes netcat
      #  This allows polling the DB port to confirm it is open before proceedingd
    - run:
        name: Waiting for MySQL to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 3306 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for MySQL && exit 1

    - run:
        name: run build
        command: |
          dep ensure
          go build ./...
    - run:
        name: Ensure correctly vetted code
        command: go vet ./...
    - run:
        name: Ensure correctly linted (go fmt)
        command: go fmt ./...
    - run:
        name: Run go tests
        command: go test ./...