version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.1
    - image: circleci/mysql:5.7

    working_directory: /go/src/github.com/VerstraeteBert/WeatherApp
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/cmd/dep
    - run: go get github.com/golang-migrate/migrate/cli
    - run: go get -u github.com/go-sql-driver/mysql

      #  CircleCi's Go Docker image includes netcat
      #  This allows polling the DB port to confirm it is open before proceedingd
    - run:
        name: Waiting for MySQL to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 3306 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for MySQL && exit 1

    - run:
        name: run build
        command: |
          dep ensure
          go build ./...
    - run:
        name: Ensure correctly vetted code
        command: go vet ./...
    - run:
        name: Ensure correctly linted (go fmt)
        command: go fmt ./...
    - run:
        name: Run go tests
        command: |
          go build -tags 'mysql' -o ./migrate /go/src/github.com/golang-migrate/migrate/cli
          ./migrate -database "mysql://root:@tcp(localhost:3306)/circle_test" -path ./migrations up
          go test ./...
        environment:
          DATABASE_URL: root:@tcp(localhost:3306)/circle_test