# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    # specify the version
    - image: circleci/golang:1.11.1

    working_directory: /go/src/github.com/WeatherApp
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/cmd/dep
    - run:
        name: run build
        command: |
          dep ensure
          go build ./...
    - run:
        name: Ensure Correctly Linted Go Packages
        command: "! go fmt ./... 2>&1 | read"
    - run:
        name: Ensure correctly Vetted Go Code
        command: "go vet ./..."
